# Site settings
title: Sunder
header-img: "img/tree.jpg"
tagline: "吉光片羽"  
description: "后之视今，亦犹今之视昔"
baseurl: ""
url: "https://xiangrongzeng.github.io/"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Sunder"
  email: 1111@sss.cmo
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/cat_favicon.ico

douban_username: Sunder
twitter_username: Sunder  
github_username: Sunder  
facebook_username: Sunder  
weibo_username: Sunder  
zhihu_username: Sunder  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Sunder/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sunder"
      header-img: "img/grass.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Sunder
  disqus :
      short_name : Sunder

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation